-- [1] DISPLAY ENTIRE DATA FROM PRODUCTS TABLE
SELECT *
FROM Product;

-- [2] DISPLAY ONLY ADDRESS_ID, CITY AND PINCODE COLUMNS FROM ADDRESS TABLE
SELECT ADDRESS_ID, CITY, PINCODE
FROM address;


-- [3] DISPLAY UNIQUE CITIES IN THE ADDRESS TABLE
SELECT DISTINCT CITY
FROM address;

-- [4] DELETE ALL THE RECORDS FROM PRODUCTS TABLE WHOSE PRODUCT_ID IS 99999
DELETE
FROM product
WHERE Product_ID = 99999;
SELECT *
FROM Product

-- [5] UPDATE THE PRICE OF ALL PRODUCTS IN THE PRODUCTS TABLE TO 25% LESSER VALUE 
-- SET SQL_SAFE_UPDATES = 0
UPDATE product
SET PRODUCT_PRICE = PRODUCT_PRICE - (PRODUCT_PRICE*0.25);
SELECT *
FROM product;



-- [6] DISPLAY THE TOP 10 ROWS FROM ADDRESS TABLE
SELECT *
FROM address
LIMIT 10;


